// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An archived page.
 */
export type ArchivedPage = { short_id: string, slug: string, title: string, archived_at: string, archived_by_name: string | null, };
