// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthConfig = { 
/**
 * Whether "Sign in with Google" is available.
 */
google: boolean, };
