// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryValue } from "./CategoryValue";
import type { TopicRef } from "./TopicRef";

export type Category = { id: string, name: string, description: string, required_everywhere: boolean, 
/**
 * Pages in these topics, or their sub-topics, need a value.
 */
required_topics: Array<TopicRef>, 
/**
 * In the order people pick from.
 */
values: Array<CategoryValue>, 
/**
 * Pages that need a value here and don't have one.
 */
missing_count: number, };
