// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagColor } from "./TagColor";

export type CategoryValue = { id: string, name: string, color: TagColor, 
/**
 * Pages with this value.
 */
page_count: number, };
