// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateTopicRequest = { name: string, description: string, 
/**
 * Absent for a top-level topic.
 */
parent_id: string | null, };
