// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateTemplateRequest = { name: string, description?: string, title?: string, body_md?: string, 
/**
 * Preset topics, e.g. those of the page being saved as a template.
 */
topic_ids?: Array<string>, tag_names?: Array<string>, };
