// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatePageRequest = { title: string, body_md: string, 
/**
 * Start from this template instead of `body_md`; `title` is used when the
 * template doesn't set one.
 */
template_id?: string, 
/**
 * Topics to put the page in, on top of any the template presets.
 */
topic_ids?: Array<string>, 
/**
 * The writer's local date (YYYY-MM-DD) for {{date}}; defaults to today in UTC.
 */
local_date?: string, };
