// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagColor } from "./TagColor";

export type CreateValueRequest = { name: string, color?: TagColor, };
