// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorDetail = { 
/**
 * Machine-readable, such as `not_found`.
 */
code: string, 
/**
 * Human-readable, safe to show to the user.
 */
message: string, };
