// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InviteStatus } from "./InviteStatus";
import type { Role } from "./Role";

/**
 * What the invitation page shows before anyone signs in.
 */
export type InvitePreview = { org_name: string, email: string, role: Role, invited_by_name: string, status: InviteStatus, 
/**
 * Whether an account with the invited address exists (sign in vs. sign up).
 */
account_exists: boolean, };
