// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Membership } from "./Membership";
import type { User } from "./User";

/**
 * The signed-in user and the organizations they belong to.
 */
export type Me = { user: User, orgs: Array<Membership>, };
