// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type Member = { user_id: string, name: string, email: string, avatar_url: string | null, role: Role, joined_at: string, };
