// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * An organization as seen by one of its members.
 */
export type Membership = { id: string, name: string, slug: string, role: Role, };
