// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MergeTagRequest = { 
/**
 * The tag that stays; pages tagged with the merged tag get this one.
 */
into_id: string, };
