// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MoveTopicRequest = { 
/**
 * The new parent; absent to make it a top-level topic.
 */
parent_id: string | null, 
/**
 * Where among its new siblings it goes, 0 being first.
 */
index: number, };
