// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An email the app sent (or would have sent), as the outbox shows it.
 */
export type OutboxEmail = { to: string, subject: string, body: string, sent_at: string, };
