// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagColor } from "./TagColor";

/**
 * A page's value in a list.
 */
export type PageValue = { category: string, id: string, name: string, color: TagColor, };
