// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A page in a list.
 */
export type PageSummary = { short_id: string, slug: string, 
/**
 * The published title, or the draft's for a page never published.
 */
title: string, published: boolean, 
/**
 * Whether there are unpublished changes.
 */
has_draft: boolean, updated_at: string, updated_by_name: string, };
