// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Version } from "./Version";

export type PageDetail = { id: string, short_id: string, slug: string, 
/**
 * What readers see; absent until the page is first published.
 */
published: Version | null, published_at: string | null, published_by_name: string | null, 
/**
 * Unpublished changes, when there are any.
 */
draft: Version | null, created_at: string, };
