// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueRef } from "./ValueRef";

/**
 * One category as it applies to a page.
 */
export type PageCategory = { category_id: string, name: string, 
/**
 * Whether the page must have a value before it can be published.
 */
required: boolean, value: ValueRef | null, 
/**
 * The values to choose from.
 */
options: Array<ValueRef>, };
