// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type PendingInvite = { id: string, email: string, role: Role, invited_by_name: string, created_at: string, expires_at: string, };
