// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublishRequest = { 
/**
 * The draft revision the person reviewed; publishing fails if it changed.
 */
revision_id: string, };
