// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A page title for the quick-open box.
 */
export type QuickPage = { short_id: string, slug: string, title: string, published: boolean, };
