// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuickPage } from "./QuickPage";
import type { TopicRef } from "./TopicRef";

export type QuickResults = { topics: Array<TopicRef>, pages: Array<QuickPage>, };
