// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RestoreRevisionRequest = { 
/**
 * The page's current revision when the person chose to restore; a newer
 * one means someone saved in between, and the restore is refused.
 */
base_revision_id: string, };
