// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevisionSummary } from "./RevisionSummary";
import type { Version } from "./Version";

/**
 * A revision with its content, and the one before it to compare with.
 */
export type RevisionDetail = { revision: RevisionSummary, body_md: string, previous: Version | null, };
