// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One revision in a page's history.
 */
export type RevisionSummary = { revision_id: string, title: string, author_name: string, created_at: string, 
/**
 * The last save into this revision.
 */
updated_at: string, 
/**
 * When it went live, even if a later version has replaced it since.
 */
published_at: string | null, published_by_name: string | null, 
/**
 * When the draft it belonged to was discarded.
 */
discarded_at: string | null, 
/**
 * The earlier revision it was restored from, and that revision's last save.
 */
restored_from: string | null, restored_from_at: string | null, 
/**
 * What readers see now.
 */
is_live: boolean, 
/**
 * What editors work on now: the draft, or the live version when there is no draft.
 */
is_current: boolean, };
