// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of saving a draft.
 */
export type SavedDraft = { 
/**
 * Send this as `base_revision_id` with the next save.
 */
revision_id: string, updated_at: string, };
