// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveDraftRequest = { 
/**
 * The revision the editor started from; a different current revision
 * means someone else saved in between, and the save is refused.
 */
base_revision_id: string, title: string, body_md: string, };
