// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageValue } from "./PageValue";
import type { TagRef } from "./TagRef";
import type { TopicRef } from "./TopicRef";

/**
 * A page that matched, best first.
 */
export type SearchHit = { short_id: string, slug: string, 
/**
 * The title with matches between `\u0002` and `\u0003`.
 */
title: string, 
/**
 * Words around the matches in the body, marked the same way.
 */
snippet: string, published: boolean, updated_at: string, updated_by_name: string, topics: Array<TopicRef>, tags: Array<TagRef>, values: Array<PageValue>, };
