// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchHit } from "./SearchHit";
import type { TopicRef } from "./TopicRef";

export type SearchResults = { 
/**
 * Topics whose names match.
 */
topics: Array<TopicRef>, pages: Array<SearchHit>, 
/**
 * What the query's filters were understood as, such as "Topic: Engineering".
 */
scope: Array<string>, 
/**
 * Filters in the query that matched nothing, such as `topic:nope`.
 */
unmatched: Array<string>, };
