// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetPageCategoryRequest = { category_id: string, 
/**
 * Absent to clear the page's value.
 */
value_id: string | null, };
