// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetPageTagsRequest = { 
/**
 * Tag names; names that don't match a tag yet create one.
 */
names: Array<string>, };
