// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SignupRequest = { name: string, email: string, password: string, 
/**
 * Signing up from an invitation sent to this same address proves the
 * address, so no confirmation email is needed.
 */
invite_token?: string, };
