// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagColor } from "./TagColor";

/**
 * A tag on a page.
 */
export type TagRef = { id: string, name: string, slug: string, color: TagColor, };
