// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A template in a list or the New page picker.
 */
export type TemplateSummary = { id: string, name: string, description: string, 
/**
 * The new page's title, placeholders unfilled; empty to let the writer choose.
 */
title: string, 
/**
 * Whether the text uses {{title}}, which needs the title before the page starts.
 */
uses_title: boolean, updated_at: string, updated_by_name: string, };
