// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageSummary } from "./PageSummary";
import type { Topic } from "./Topic";
import type { TopicRef } from "./TopicRef";

export type TopicDetail = { topic: Topic, 
/**
 * Ancestors, the root first.
 */
path: Array<TopicRef>, children: Array<Topic>, pages: Array<PageSummary>, };
