// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enough of a topic to link to it.
 */
export type TopicRef = { id: string, short_id: string, slug: string, name: string, };
