// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A topic in the tree. The whole tree is small enough to send at once.
 */
export type Topic = { id: string, short_id: string, slug: string, parent_id: string | null, name: string, description: string, position: number, 
/**
 * Pages directly in this topic, not counting sub-topics.
 */
page_count: number, };
