// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateTemplateRequest = { name: string, description: string, title: string, body_md: string, };
