// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateCategoryRequest = { name?: string, description?: string, required_everywhere?: boolean, required_topic_ids?: Array<string>, };
