// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An uploaded file; `url` is what page markdown links to.
 */
export type UploadedFile = { id: string, url: string, name: string, content_type: string, size: number, };
