// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type User = { id: string, email: string, name: string, avatar_url: string | null, email_verified: boolean, };
