// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One version of a page's content.
 */
export type Version = { revision_id: string, title: string, body_md: string, author_name: string, updated_at: string, };
